"""Initial migration

Revision ID: 6a7d0b5da5cc
Revises: a64a2271795a
Create Date: 2025-10-09 17:05:08.992486-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7d0b5da5cc'
down_revision = 'a64a2271795a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
