"""Initial migration

Revision ID: c49f30a471b6
Revises: 6a7d0b5da5cc
Create Date: 2025-10-09 17:09:47.162991-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49f30a471b6'
down_revision = '6a7d0b5da5cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
