"""Initial migration

Revision ID: fca9db5b2821
Revises: 851e67a21515
Create Date: 2025-10-09 21:10:00.977508-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca9db5b2821'
down_revision = '851e67a21515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
