"""Initial migration

Revision ID: afd5510732a4
Revises: c49f30a471b6
Create Date: 2025-10-09 17:12:31.797820-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd5510732a4'
down_revision = 'c49f30a471b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
