"""Initial migration

Revision ID: a64a2271795a
Revises: f7e14a30784a
Create Date: 2025-10-09 17:00:27.875219-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64a2271795a'
down_revision = 'f7e14a30784a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
