"""Initial migration

Revision ID: 851e67a21515
Revises: 1fd9ae10100d
Create Date: 2025-10-09 21:02:30.143352-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851e67a21515'
down_revision = '1fd9ae10100d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
