"""Initial migration

Revision ID: 1fd9ae10100d
Revises: afd5510732a4
Create Date: 2025-10-09 17:16:57.895395-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9ae10100d'
down_revision = 'afd5510732a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
