"""Initial migration

Revision ID: f7e14a30784a
Revises: 8e27eeddde66
Create Date: 2025-10-09 14:07:25.678019-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e14a30784a'
down_revision = '8e27eeddde66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
